# directory with input .txt files
inputDir: input
outputDir: output

# initial field
initialBeamWidth: 800
initialWavelength: 83
initialPolarization: TE
initialAngles: 5.0 10.0 15.0 20.0

# numeric solver
gpu: true
lmax: 3

# solution grid
GridScale: 0.7
GridSize: 5500
GridStep: 8.0 # 4.0 previously