# directory with input .txt files
inputDir: input
outputDir: output

# initial field
initialBeamWidth: 800
initialWavelength: 83 #103.75 92.2 83 75.45 69.16
initialPolarization: TE
theta0: 63.3
phi0: 45

# numeric solver
gpu: true
lmax: 3

# solution grid
GridScale: 1.0
GridSize: 8000
GridStep: 80.0 # 4.0 previously