# directory with input .txt files
inputDir: input
outputDir: output

# initial field
initialBeamWidth: 800
initialWavelength: 83
initialPolarization: TE
initialAngles: 14.78

# numeric solver
gpu: true
lmax: 3

# solution grid
GridScale: 1.0
GridSize: 8000
GridStep: 80.0 # 4.0 previously