# directory with input .txt files
inputDir: input
outputDir: output

# initial field
initialBeamWidth: 800
initialWavelength: 103.75 92.2 83 75.45 69.16 # 8 9 10 11 12 harmonics
initialPolarization: TE
initialAngles: 15

# numeric solver
gpu: true
lmax: 3

# solution grid
GridScale: 1.0
GridSize: 8000
GridStep: 80.0 # 4.0 previously