# configuration file for celes (mstm)

initialParameters:
  beamWidth: 800
  wavelength: 
    - 83
    - 830
  polarization: TE
  angles: 
    - 10.0
    - 14.324
    - 20.0

numerics:
  gpu: true
  lmax: 3

solGrid:
  scale: 0.7
  size: 5500
  step: 4.0

dataFiles:
  - abc.txt