initialBeamWidth: 800
initialWavelength: 83 830
initialPolarization: TE
initialAngles: 10.0 14.324 20.0
gpu: true
lmax: 3
GridScale: 0.7
GridSize: 5500
GridStep: 4.0
datafiles: input/test_particles.txt